### PR TITLE
[minor] Add Health to FVT pipeline

### PR DESCRIPTION
**Pull request by karlinglee93**
add configurations in fvt.yml and create health.yml file for the new health pipeline repos to fvt pipeline.

### CODE REVIEW

**Review by whitfiea — COMMENTED** [review]
@karlinglee93 Can you add a description into the first section of this PR of what this PR adds, and update the title to be more descriptive, thanks.

**Comment by karlinglee93** [comment]
> @karlinglee93 Can you add a description into the first section of this PR of what this PR adds, and update the title to be more descriptive, thanks.

Hi @whitfiea , please check.

**Review by whitfiea — APPROVED** [review]
Looks ok to me. @alequint are you happy for this to be merged?

**Review by durera — COMMENTED** [review]
This creates new task definitions for Health FVT, but doesn't seem to add them into the FVT pipeline, is there a commit missing here that wasn't checked in perhaps?

**Review by durera — APPROVED** [review]

**Pull request merged**
