### PR TITLE
[patch] sps manage

### PR DESCRIPTION
**Pull request by ypkim-github**
- Triggering the dynamic scan for manage on SPS
- All same with https://github.com/ibm-mas/cli/tree/master/tekton/src/pipelines/taskdefs/ivt-core except for calling `ibmcloud dev tekton-trigger`

### CODE REVIEW

**Review by whitfiea — DISMISSED** [review]
@ypkim-github this needs a description of that this PR does and how it is tested etc. You also need to make sure it doesn't use personal image builds like `fvt-ibm-mas-manage:2.6.1-pre.vncupdates`

**Review by durera — COMMENTED** [review]
In addition to Andrew's comments, looking at the changes I don't think this will work in fvt-airgap.

- use of the ubuntu image will require that is mirrored too and a ISCP set up for it, would be better off using the CLI image seeing as it already have the tools you are installing onto the ubuntu image anyway
- use of hardcoded artifactory for the registry won't work because artifactory is blocked

**Comment by ypkim-github** [comment]
@durera @whitfiea

1. Any idea with this build-cli error?
 ```
Error parsing reference: "quay.io/ibmmas/cli:" is not a valid repository/tag: invalid reference format
```
2. How do we get the public endpoint of the cluster that is just provisioned? e.g., $(params.fvt_extenernal_host)
3. How do we make this task run only on the FVT clusters?

**Comment by whitfiea** [comment]
@ypkim-github the error `Error parsing reference: "quay.io/ibmmas/cli:" is not a valid repository/tag: invalid reference format` is becuase you have no commit messages with a [patch] (just the PR title has it). So no version can be determined.

I don't know about the other questions. You would need to ask @alequint

**Pull request closed without merging**
