### PR TITLE
[minor]  Capture DB2 and kafka versions

### PR DESCRIPTION
**Pull request by creyesibm**
Added code to get db2 cluster version and db2 operator version, also added code to find the kafka provider and its version. 
I will add test evidence once we run the code in the pipeline, local tests work as expected.

### CODE REVIEW

**Comment by creyesibm** [comment]
@alequint @durera the code is ready, there seems to be a build issue right now but it has nothing to do with the code itself, it is a problem trying to upload the docker image. If you could please review so that I can work on the changes to have them ready for when the build works. Thank you

**Comment by alequint** [comment]
@creyesibm let's redirect to he PR to managephase5 and we can test that in fvtnocpd. Then you can check if your version of dashboard will visualize the versions as expected. If that work we can go ahead and merge dashboard changes :+1:

**Comment by alequint** [comment]
@creyesibm also, please rename your branch to be all lower case, I think that is what is causing the erorrs in CLI build

**Comment by alequint** [comment]
Replaced by https://github.com/ibm-mas/cli/pull/858

**Pull request closed without merging**
