### PR TITLE
[minor] Add configuration to use jms for Manage workspace configuration

### PR DESCRIPTION
**Pull request by caroazad**
Added params for MAS_APP_SETTINGS_PERSISTENT_VOLUMES_FLAG and MAS_APP_SETTINGS_SERVER_BUNDLES_SIZE.
- configured in install-with-fvt
- prompt for confirmation

Test completed with jms configured and without jms configured. Here are some screenshots. I have a cluster under the name of testjms, which has two instances that test the configurations. (It will stay up until this story closes for verification purposes)
Image 1: Prompt on CLI to configure JMS
Image 2: Volumes in Maxinst deployment
Image 3: Persistent Volumes in manage namespace
Image 4: No JMS Configuration Maxinst deployment volumes

Screenshot 2023-02-09 at 9 01 48 AM
Screenshot 2023-02-09 at 9 07 34 AM
Screenshot 2023-02-09 at 9 09 34 AM
Screenshot 2023-02-09 at 11 01 09 AM

### CODE REVIEW

**Comment by caroazad** [comment]
Test on fvt pipeline was also successful with the changes.

**Review by alequint — APPROVED** [review]
Looks good to me

**Comment by alequint** [comment]
@durera this PR is a necessary setup for Monitor integration tests with Manage. Basically it uses a feature already implemented and release in ansible-devops to setup JMS queues in Manage (FYI). It is needed to finalize Monitor MVT epic.

**Comment by alequint** [comment]
@caroazad could you please solve conflict between this and master branch?

**Review by alequint — DISMISSED** [review]

**Review by alequint — APPROVED** [review]

**Pull request merged**
