### PR TITLE
[patch] Updated DRO migration checks

### PR DESCRIPTION
**Pull request by yuvraj-vansure**
[MASCORE-2328](https://jsw.ibm.com/browse/MASCORE-2328):
- install_config_storage_classes internal function to get storageclass.
- skip uds/dro pipeline task if dro_migration is not true

### CODE REVIEW

**Review by lokesh-sreedhara — DISMISSED** [review]

**Comment by andrercm** [comment]
@yuvraj-vansure @lokesh-sreedhara Would you guys be able to place a screenshot of the tested change?
We need to make sure that new texts added via `echo` follows same formatting standards... as example: https://github.com/ibm-mas/cli/blob/master/image/cli/mascli/functions/internal/install_config_storage_classes#L60

**Review by andrercm — CHANGES_REQUESTED** [review]
@yuvraj-vansure @lokesh-sreedhara Would you guys be able to place a screenshot of the tested change?
We need to make sure that new texts added via echo follows same formatting standards... as example: https://github.com/ibm-mas/cli/blob/master/image/cli/mascli/functions/internal/install_config_storage_classes#L60

**Comment by yuvraj-vansure** [comment]
> @yuvraj-vansure @lokesh-sreedhara Would you guys be able to place a screenshot of the tested change? We need to make sure that new texts added via echo follows same formatting standards... as example: https://github.com/ibm-mas/cli/blob/master/image/cli/mascli/functions/internal/install_config_storage_classes#L60

- Use auto-detected storageclass
image
- Use own storageclass
image

- no-confirm without `--dro_migration` flag
image

- `--no-confirm` & `--dro-migration` without ` --dro-storage-class`
image


- `--no-confirm` & `--dro-migration` with ` --dro-storage-class`
image

**Review by andrercm — APPROVED** [review]
Thanks for the screenshots these help a lot understand the whole flow.
Looks good.

**Pull request merged**
