### PR TITLE
[minor] Civil FVT Launcher and Civil Pipeline

### PR DESCRIPTION
**Pull request by erikfi**

### CODE REVIEW

**Comment by alequint** [comment]
@erikfi I wll review this PR now that mine has been merged and address conflicts at the same time. I believe we will need a new cycle of tests once I am done here to guarantee civil is working fine with the other things in my previous PR :+1: - I will work with it today

**Comment by leo-miran** [comment]
I'm currently testing this branch in personal cluster mobci in IBM Cloud.

**Comment by leo-miran** [comment]
@alequint my test today was successful. 
image

**Comment by alequint** [comment]
@erikfi @Leo-Miranda I have merged master into your branch. Used your secret, launcher etc for civil but changed two things:
- References to fvt-civil replaced by fvt-manage-civil (as Civil is still an add-on of Manage)
- Added black/white list references for civil wherever it missed

Just need to retest now to be sure it still works end to end.

Evidence of tests on tekton resources:

```
 - Adding Pipeline: /Users/alequint/Documents/projects/mas/tasks/manageis/cli/tekton/target/pipelines/update.yaml
pipeline.tekton.dev/mas-update created
 - Adding Pipeline: /Users/alequint/Documents/projects/mas/tasks/manageis/cli/tekton/target/pipelines/upgrade-after-install.yaml
pipeline.tekton.dev/mas-upgrade-after-install created
 - Adding Pipeline: /Users/alequint/Documents/projects/mas/tasks/manageis/cli/tekton/target/pipelines/upgrade.yaml
pipeline.tekton.dev/mas-upgrade created
alequint@Alexandres-MBP tekton % 
```

**Comment by leo-miran** [comment]
Latest test was successful
image
image

**Review by leo-miran — DISMISSED** [review]

**Review by alequint — APPROVED** [review]

**Pull request merged**
