### PR TITLE
[patch] Add mongodb_version to update pipelinerun

### PR DESCRIPTION
**Pull request by whitfiea**
The mongodb_version was missing from the pipelinerun for update, so when the cli sets it here https://github.com/ibm-mas/cli/blob/c602b9db623448dc8dd324da76c4ae3433db4032/image/cli/mascli/functions/update#L686 it is then not set in the pipelinerun for update as it was missing.

### CODE REVIEW

**Comment by HarveyTangg** [comment]
I found that 'mongodb_version' is also missing in the 'mas-update' pipeline definition. So, probably /tekton/src/pipelines/update.yml.js also needs to be updated?

**Review by andrercm — DISMISSED** [review]
good catch

**Comment by andrercm** [comment]
can you also add `MONGODB_V6_UPGRADE` in there?

**Comment by whitfiea** [comment]
@andrercm can you review again please?. This is now verified to work.

**Review by andrercm — APPROVED** [review]

**Pull request merged**
