### PR TITLE
[minor] Manage FVT Task, Parameter and Pipeline updates

### PR DESCRIPTION
**Pull request by leo-miran**
Added new Tasks and parameters for the following Industry Solutions:
- Scheduler
- Maintenanca Manager
- Inventory Counting

Also added new setup tasks for:
- ACM
- Service Provider
- Transportation
- Scheduler
- Mobile

Screenshot from a successful execution in test cluster fvtistkn3
Screenshot 2022-12-22 at 15 34 46

### CODE REVIEW

**Review by alequint — DISMISSED** [review]

**Comment by leo-miran** [comment]
New successfully test after recents merges to this branch
image

**Comment by leo-miran** [comment]
This is the result of my most recent test with the latest updates.
Screenshot 2023-02-01 at 07 32 11
@durera do you think this is in a good state to be merged?

**Comment by alequint** [comment]
@leo-miran as this is a minor version, could you please update change log here of what is coming in this `3.12` ? https://github.com/ibm-mas/cli/blob/master/docs/changes.md

**Review by alequint — APPROVED** [review]

**Comment by leo-miran** [comment]
This is the equivalent pr for ansible-fvt
https://github.ibm.com/maximoappsuite/ansible-fvt/pull/128

**Review by durera — APPROVED** [review]

**Pull request merged**
