### PR TITLE
[patch][mascore-2038] control install order of MAS applications

### PR DESCRIPTION
**Pull request by racree**
Deploy MAS applications in a certain order and wait for each to be healthy before continuing to the next.  Replace the current installation ApplicationSet with an Application per MAS app, assigning the appropriate syncwave to each.

### CODE REVIEW

**Comment by racree** [comment]
Started container for quay.io/ibmmas/cli:8.1.0-pre.mascore2038
Executed
`mas gitops-suite-app-install --mas-app-id monitor --account-id fyre-dev-2 --cluster-id noble3 --region us-east-2 --mas-instance-id inst1 --mas-app-channel MY_CHANNEL --mas-app-catalog-source MY_CATALOG --mas-app-api-version MY_API_VERSION --mas-app-kind MonitorAPP`

Verified generated file has the correct name and stored in the correct directory.
`./working-dir/fyre-dev-2/us-east-2/noble3/inst1/masapps/ibm-mas-masapp-monitor-install.yaml`

Similarly I executed
`DEFAULT_FILE_STORAGE_CLASS=STORAGE_CLASS mas gitops-suite-app-install --mas-app-id visualinspection --account-id fyre-dev-2 --cluster-id noble3 --region us-east-2 --mas-instance-id inst1 --mas-app-channel MY_CHANNEL --mas-app-catalog-source MY_CATALOG --mas-app-api-version MY_API_VERSION --mas-app-kind VisualinspectionApp `

and verified the generated file has the correct name and stored in the correct directory.
`./working-dir/fyre-dev-2/us-east-2/noble3/inst1/masapps/ibm-mas-masapp-visualinspection-install.yaml`

**Comment by racree** [comment]
This PR goes with https://github.com/ibm-mas/gitops/pull/50

**Review by whitfiea — CHANGES_REQUESTED** [review]
It looks like we have changed the name of the argo app for the mas apps. So instead of "ma.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}.assist" it is now "assist.{{.Values.account.id}}.{{.Values.region.id}}.{{ .Values.cluster.id }}.{{ .Values.instance.id }}" but we still have a number of places in the cli that use the old `ma.` name. Can we change these as well?

**Comment by racree** [comment]
@whitfiea I made these updates per your comment...
```
./image/cli/mascli/functions/gitops_deprovision_app_install
246:      MASAPP_APP="${MAS_APP_ID}.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

./image/cli/mascli/functions/gitops_deprovision_app_config
257:      MASAPP_APP="${MAS_WORKSPACE_ID}.${MAS_APP_ID}.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

./image/cli/mascli/functions/gitops_suite_app_install
349:  MASAPP_APP="${MAS_APP_ID}.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

./image/cli/mascli/functions/gitops_suite_app_config
401:  MASAPP_APP="${MAS_WORKSPACE_ID}.${MAS_APP_ID}.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

./tekton/src/tasks/gitops/gitops-mas-fvt-preparer.yml.j2
401:            MASAPP_APP="assist.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}"
405:            MASAPP_APP="iot.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}"
409:            MASAPP_APP="manage.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}"
413:            MASAPP_APP="manage.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}"
417:            MASAPP_APP="monitor.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}"
421:            MASAPP_APP="optimizer.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}"
425:            MASAPP_APP="predict.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}"
429:            MASAPP_APP="visualinspection.${ACCOUNT_ID}.${REGION_ID}.${CLUSTER_NAME}.${MAS_INSTANCE_ID}"
```

**Comment by racree** [comment]
Verified config of 2 IoT workspaces.
image

**Pull request merged**
